name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ "gh-pages" ]  # Change to your primary branch if different

jobs:
  build-and-deploy:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: false
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Build the app
        run: npm run build
        env:
          CI: false
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          CI: false
          GH_PAT: ${{ secrets.GH_PAT }}
